-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Wed Sep 19 10:51:57 2012
--   Input Files:       /home/strobl/Datenbankschema-17.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia

-- alter table call drop constraint call_fk_Caller_id-- (is implicitly done)
-- alter table caller_whitelist drop constraint caller_whitelist_fk_Caller_id-- (is implicitly done)
-- alter table caller_blacklist drop constraint caller_blacklist_fk_Caller_id-- (is implicitly done)
-- alter table caller_blacklist drop constraint caller_blacklist_fk_Call_id-- (is implicitly done)
-- alter table callee_whitelist drop constraint callee_whitelist_fk_Callee_id-- (is implicitly done)
-- alter table matchlist drop constraint matchlist_fk_Call_id-- (is implicitly done)
-- alter table matchlist drop constraint matchlist_fk_Matched_call_id-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia

drop view v_caller_blacklist cascade ;
drop view v_callee_whitelist cascade ;


-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia

drop table caller_whitelist cascade ;
drop table caller_blacklist cascade ;
drop table caller cascade ;
drop table call cascade ;
drop table callee_whitelist cascade ;
drop table callee cascade ;
drop table matchlist cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia


-- caller_whitelist
create table caller_whitelist (
  caller_id                 integer
) ;

-- caller_blacklist
create table caller_blacklist (
  caller_id                 integer,
  call_id                   integer,	-- Der Call der zum Blacklisteintrag gefuehrt hat.
  old_call_id               integer,
  timestamp                 timestamp,
  reason                    varchar(50)
) ;

-- caller
create table caller (
  id                        serial not null,
  name                      varchar(60),
  uri                       varchar(100),
  constraint pk_Caller primary key (id)
) ;

-- call
create table call (
  id                        serial not null,
  caller_id                 integer not null,
  timestamp                 timestamp,
  processed                 smallint default -1,
  indexed                   smallint,
  constraint pk_Call primary key (id)
) ;

-- callee_whitelist
create table callee_whitelist (
  callee_id                 integer
) ;

-- callee
create table callee (
  id                        serial not null,
  uri                       varchar(100),
  constraint pk_Callee primary key (id)
) ;

-- matchlist
create table matchlist (
  call_id                   integer,
  matched_call_id           integer,
  length_query              smallint not null,
  actual_mismatches         smallint not null,
  offset_position           smallint not null
) ;

comment on column caller_blacklist.call_id is 'Der Call der zum Blacklisteintrag gefuehrt hat.';








-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia


-- v_caller_blacklist
create view v_caller_blacklist as
  select caller.*
  from caller, caller_blacklist
  where caller_blacklist.caller_id not in (select caller_id from caller_whitelist) AND caller_blacklist.caller_id=caller.id
;

-- v_callee_whitelist
create view v_callee_whitelist as
  select callee.uri
  from callee, callee_whitelist
  where callee_whitelist.callee_id=callee.id
;



-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Sep 19 10:51:56 2012
--     Input Files:       /home/strobl/Datenbankschema-17.dia

alter table call add constraint call_fk_Caller_id
  foreign key (caller_id)
  references caller (id)  ;
alter table caller_whitelist add constraint caller_whitelist_fk_Caller_id
  foreign key (caller_id)
  references caller (id)  ;
alter table caller_blacklist add constraint caller_blacklist_fk_Caller_id
  foreign key (caller_id)
  references caller (id)  ;
alter table caller_blacklist add constraint caller_blacklist_fk_Call_id
  foreign key (call_id)
  references call (id)  ;
alter table callee_whitelist add constraint callee_whitelist_fk_Callee_id
  foreign key (callee_id)
  references callee (id)  ;
alter table matchlist add constraint matchlist_fk_Call_id
  foreign key (call_id)
  references call (id)  ;
alter table matchlist add constraint matchlist_fk_Matched_call_id
  foreign key (matched_call_id)
  references call (id)  ;

